image: python:latest
pages:
  stage: deploy
  only:
    - master 
    - main
  script:
    - pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
